name: CI clock-service

on:
  push:
    paths: ['clock-service/**']
  pull_request:
    branches: [main]
    paths: ['clock-service/**']

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clock-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: clock-service/package-lock.json
      - run: npm ci
      - name: Run Tests with Coverage
        run: npm test -- --coverage --coverageReporters=text-summary
      - run: npm run lint
